version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/miadb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
    depends_on:
      - db
  db:
    image: "postgres:14-alpine"
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=miadb
volumes:
  postgres_data: