version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/target
      - app-data:/app-data
    depends_on:
      - db
  db:
    image: "postgres:14-alpine"
    ports:
      - "5433:5433"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=miadb
volumes:
  postgres_data:
  app-data:
